### ISSUE TITLE
Add doctype to index.html

### ISSUE THREAD

**Issue by nicksuch** [dhopwood/dhopwood.github.io#2]
Hey @dhopwood - your about me page looks great! Looking forward to helping you accomplish the goals you've listed, especially "changing the world with your dogs"

One fix for your page - add in a `<!DOCTYPE html>` on the very first line. This helps a user's web browser know what type of page you've created: https://developer.mozilla.org/en-US/docs/Glossary/Doctype

All else looks good, keep it up!

**Comment by dhopwood** [comment]
+1
